/**
 * Slice Doc Library - T3
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FileTransferResult model module.
 * @module model/FileTransferResult
 * @version 1.0.0
 */
class FileTransferResult {
    /**
     * Constructs a new <code>FileTransferResult</code>.
     * @alias module:model/FileTransferResult
     * @param result {Object} 
     */
    constructor(result) { 
        
        FileTransferResult.initialize(this, result);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, result) { 
        obj['result'] = result;
    }

    /**
     * Constructs a <code>FileTransferResult</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FileTransferResult} obj Optional instance to populate.
     * @return {module:model/FileTransferResult} The populated <code>FileTransferResult</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FileTransferResult();

            if (data.hasOwnProperty('result')) {
                obj['result'] = ApiClient.convertToType(data['result'], Object);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} result
 */
FileTransferResult.prototype['result'] = undefined;






export default FileTransferResult;

