/**
 * Slice Doc Library - T3
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GdriveClientCredentials model module.
 * @module model/GdriveClientCredentials
 * @version 1.0.0
 */
class GdriveClientCredentials {
    /**
     * Constructs a new <code>GdriveClientCredentials</code>.
     * @alias module:model/GdriveClientCredentials
     * @param clientId {String} 
     * @param clientSecret {String} 
     * @param redirectUris {String} 
     */
    constructor(clientId, clientSecret, redirectUris) { 
        
        GdriveClientCredentials.initialize(this, clientId, clientSecret, redirectUris);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, clientId, clientSecret, redirectUris) { 
        obj['client_id'] = clientId;
        obj['client_secret'] = clientSecret;
        obj['redirect_uris'] = redirectUris;
    }

    /**
     * Constructs a <code>GdriveClientCredentials</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GdriveClientCredentials} obj Optional instance to populate.
     * @return {module:model/GdriveClientCredentials} The populated <code>GdriveClientCredentials</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GdriveClientCredentials();

            if (data.hasOwnProperty('client_id')) {
                obj['client_id'] = ApiClient.convertToType(data['client_id'], 'String');
            }
            if (data.hasOwnProperty('client_secret')) {
                obj['client_secret'] = ApiClient.convertToType(data['client_secret'], 'String');
            }
            if (data.hasOwnProperty('redirect_uris')) {
                obj['redirect_uris'] = ApiClient.convertToType(data['redirect_uris'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} client_id
 */
GdriveClientCredentials.prototype['client_id'] = undefined;

/**
 * @member {String} client_secret
 */
GdriveClientCredentials.prototype['client_secret'] = undefined;

/**
 * @member {String} redirect_uris
 */
GdriveClientCredentials.prototype['redirect_uris'] = undefined;






export default GdriveClientCredentials;

