/**
 * Slice Doc Library - T3
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import S3BucketListData from './S3BucketListData';

/**
 * The S3BucketList model module.
 * @module model/S3BucketList
 * @version 1.0.0
 */
class S3BucketList {
    /**
     * Constructs a new <code>S3BucketList</code>.
     * @alias module:model/S3BucketList
     * @param data {Array.<module:model/S3BucketListData>} 
     */
    constructor(data) { 
        
        S3BucketList.initialize(this, data);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, data) { 
        obj['data'] = data;
    }

    /**
     * Constructs a <code>S3BucketList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/S3BucketList} obj Optional instance to populate.
     * @return {module:model/S3BucketList} The populated <code>S3BucketList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new S3BucketList();

            if (data.hasOwnProperty('data')) {
                obj['data'] = ApiClient.convertToType(data['data'], [S3BucketListData]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/S3BucketListData>} data
 */
S3BucketList.prototype['data'] = undefined;






export default S3BucketList;

