/**
 * Slice Doc Library - T3
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SliceDocLibraryT3);
  }
}(this, function(expect, SliceDocLibraryT3) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SliceDocLibraryT3.GdriveToken();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GdriveToken', function() {
    it('should create an instance of GdriveToken', function() {
      // uncomment below and update the code to test GdriveToken
      //var instane = new SliceDocLibraryT3.GdriveToken();
      //expect(instance).to.be.a(SliceDocLibraryT3.GdriveToken);
    });

    it('should have the property accessToken (base name: "access_token")', function() {
      // uncomment below and update the code to test the property accessToken
      //var instance = new SliceDocLibraryT3.GdriveToken();
      //expect(instance).to.be();
    });

    it('should have the property refreshToken (base name: "refresh_token")', function() {
      // uncomment below and update the code to test the property refreshToken
      //var instance = new SliceDocLibraryT3.GdriveToken();
      //expect(instance).to.be();
    });

    it('should have the property scope (base name: "scope")', function() {
      // uncomment below and update the code to test the property scope
      //var instance = new SliceDocLibraryT3.GdriveToken();
      //expect(instance).to.be();
    });

    it('should have the property tokenType (base name: "token_type")', function() {
      // uncomment below and update the code to test the property tokenType
      //var instance = new SliceDocLibraryT3.GdriveToken();
      //expect(instance).to.be();
    });

    it('should have the property expiryDate (base name: "expiry_date")', function() {
      // uncomment below and update the code to test the property expiryDate
      //var instance = new SliceDocLibraryT3.GdriveToken();
      //expect(instance).to.be();
    });

  });

}));
