/**
 * docxlib_js
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DigimockerFile from './DigimockerFile';

/**
 * The DigiMockerFileList model module.
 * @module model/DigiMockerFileList
 * @version 1.0.0
 */
class DigiMockerFileList {
    /**
     * Constructs a new <code>DigiMockerFileList</code>.
     * @alias module:model/DigiMockerFileList
     * @param files {Array.<module:model/DigimockerFile>} 
     */
    constructor(files) { 
        
        DigiMockerFileList.initialize(this, files);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, files) { 
        obj['files'] = files;
    }

    /**
     * Constructs a <code>DigiMockerFileList</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DigiMockerFileList} obj Optional instance to populate.
     * @return {module:model/DigiMockerFileList} The populated <code>DigiMockerFileList</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DigiMockerFileList();

            if (data.hasOwnProperty('files')) {
                obj['files'] = ApiClient.convertToType(data['files'], [DigimockerFile]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<module:model/DigimockerFile>} files
 */
DigiMockerFileList.prototype['files'] = undefined;






export default DigiMockerFileList;

