/**
 * docxlib_js
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GdriveFile model module.
 * @module model/GdriveFile
 * @version 1.0.0
 */
class GdriveFile {
    /**
     * Constructs a new <code>GdriveFile</code>.
     * @alias module:model/GdriveFile
     * @param kind {String} 
     * @param id {String} 
     * @param name {String} 
     * @param mimeType {String} 
     * @param iconLink {String} 
     */
    constructor(kind, id, name, mimeType, iconLink) { 
        
        GdriveFile.initialize(this, kind, id, name, mimeType, iconLink);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, kind, id, name, mimeType, iconLink) { 
        obj['kind'] = kind;
        obj['id'] = id;
        obj['name'] = name;
        obj['mimeType'] = mimeType;
        obj['iconLink'] = iconLink;
    }

    /**
     * Constructs a <code>GdriveFile</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GdriveFile} obj Optional instance to populate.
     * @return {module:model/GdriveFile} The populated <code>GdriveFile</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GdriveFile();

            if (data.hasOwnProperty('kind')) {
                obj['kind'] = ApiClient.convertToType(data['kind'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('mimeType')) {
                obj['mimeType'] = ApiClient.convertToType(data['mimeType'], 'String');
            }
            if (data.hasOwnProperty('iconLink')) {
                obj['iconLink'] = ApiClient.convertToType(data['iconLink'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} kind
 */
GdriveFile.prototype['kind'] = undefined;

/**
 * @member {String} id
 */
GdriveFile.prototype['id'] = undefined;

/**
 * @member {String} name
 */
GdriveFile.prototype['name'] = undefined;

/**
 * @member {String} mimeType
 */
GdriveFile.prototype['mimeType'] = undefined;

/**
 * @member {String} iconLink
 */
GdriveFile.prototype['iconLink'] = undefined;






export default GdriveFile;

