/**
 * docxlib_js
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GdriveClientCredentials from './GdriveClientCredentials';
import GdriveToken from './GdriveToken';

/**
 * The InlineObject4 model module.
 * @module model/InlineObject4
 * @version 1.0.0
 */
class InlineObject4 {
    /**
     * Constructs a new <code>InlineObject4</code>.
     * @alias module:model/InlineObject4
     */
    constructor() { 
        
        InlineObject4.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>InlineObject4</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InlineObject4} obj Optional instance to populate.
     * @return {module:model/InlineObject4} The populated <code>InlineObject4</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineObject4();

            if (data.hasOwnProperty('token')) {
                obj['token'] = GdriveToken.constructFromObject(data['token']);
            }
            if (data.hasOwnProperty('gdriveClientCredentials')) {
                obj['gdriveClientCredentials'] = GdriveClientCredentials.constructFromObject(data['gdriveClientCredentials']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/GdriveToken} token
 */
InlineObject4.prototype['token'] = undefined;

/**
 * @member {module:model/GdriveClientCredentials} gdriveClientCredentials
 */
InlineObject4.prototype['gdriveClientCredentials'] = undefined;






export default InlineObject4;

