/**
 * docxlib_js
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import S3BucketList from '../model/S3BucketList';
import S3Credentials from '../model/S3Credentials';

/**
* Destinations service.
* @module api/DestinationsApi
* @version 1.0.0
*/
export default class DestinationsApi {

    /**
    * Constructs a new DestinationsApi. 
    * @alias module:api/DestinationsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the s3StorageListBuckets operation.
     * @callback module:api/DestinationsApi~s3StorageListBucketsCallback
     * @param {String} error Error message, if any.
     * @param {module:model/S3BucketList} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all s3 buckets associated with given aws credentials
     * @param {Object} opts Optional parameters
     * @param {module:model/S3Credentials} opts.s3Credentials 
     * @param {module:api/DestinationsApi~s3StorageListBucketsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/S3BucketList}
     */
    s3StorageListBuckets(opts, callback) {
      opts = opts || {};
      let postBody = opts['s3Credentials'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = S3BucketList;
      return this.apiClient.callApi(
        '/destination/s3/listBuckets', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
