/**
 * Slice Doc Library - T3
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import DigiMockerFileList from './model/DigiMockerFileList';
import DigiMockerToken from './model/DigiMockerToken';
import DigimockerFile from './model/DigimockerFile';
import FileTransfer from './model/FileTransfer';
import FileTransferResult from './model/FileTransferResult';
import FileTransferSourceConfig from './model/FileTransferSourceConfig';
import GdriveClientCredentials from './model/GdriveClientCredentials';
import GdriveFile from './model/GdriveFile';
import GdriveFileList from './model/GdriveFileList';
import GdriveToken from './model/GdriveToken';
import GdriveUrl from './model/GdriveUrl';
import InlineObject from './model/InlineObject';
import InlineObject1 from './model/InlineObject1';
import InlineObject2 from './model/InlineObject2';
import InlineObject3 from './model/InlineObject3';
import InlineObject4 from './model/InlineObject4';
import S3BucketList from './model/S3BucketList';
import S3BucketListData from './model/S3BucketListData';
import S3Credentials from './model/S3Credentials';
import DestinationsApi from './api/DestinationsApi';
import SourcesApi from './api/SourcesApi';
import TransferApi from './api/TransferApi';


/**
* This_is_api_documentation_for_slice_document_library__Team_SLICE___T3.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SliceDocLibraryT3 = require('index'); // See note below*.
* var xxxSvc = new SliceDocLibraryT3.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SliceDocLibraryT3.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SliceDocLibraryT3.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SliceDocLibraryT3.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The DigiMockerFileList model constructor.
     * @property {module:model/DigiMockerFileList}
     */
    DigiMockerFileList,

    /**
     * The DigiMockerToken model constructor.
     * @property {module:model/DigiMockerToken}
     */
    DigiMockerToken,

    /**
     * The DigimockerFile model constructor.
     * @property {module:model/DigimockerFile}
     */
    DigimockerFile,

    /**
     * The FileTransfer model constructor.
     * @property {module:model/FileTransfer}
     */
    FileTransfer,

    /**
     * The FileTransferResult model constructor.
     * @property {module:model/FileTransferResult}
     */
    FileTransferResult,

    /**
     * The FileTransferSourceConfig model constructor.
     * @property {module:model/FileTransferSourceConfig}
     */
    FileTransferSourceConfig,

    /**
     * The GdriveClientCredentials model constructor.
     * @property {module:model/GdriveClientCredentials}
     */
    GdriveClientCredentials,

    /**
     * The GdriveFile model constructor.
     * @property {module:model/GdriveFile}
     */
    GdriveFile,

    /**
     * The GdriveFileList model constructor.
     * @property {module:model/GdriveFileList}
     */
    GdriveFileList,

    /**
     * The GdriveToken model constructor.
     * @property {module:model/GdriveToken}
     */
    GdriveToken,

    /**
     * The GdriveUrl model constructor.
     * @property {module:model/GdriveUrl}
     */
    GdriveUrl,

    /**
     * The InlineObject model constructor.
     * @property {module:model/InlineObject}
     */
    InlineObject,

    /**
     * The InlineObject1 model constructor.
     * @property {module:model/InlineObject1}
     */
    InlineObject1,

    /**
     * The InlineObject2 model constructor.
     * @property {module:model/InlineObject2}
     */
    InlineObject2,

    /**
     * The InlineObject3 model constructor.
     * @property {module:model/InlineObject3}
     */
    InlineObject3,

    /**
     * The InlineObject4 model constructor.
     * @property {module:model/InlineObject4}
     */
    InlineObject4,

    /**
     * The S3BucketList model constructor.
     * @property {module:model/S3BucketList}
     */
    S3BucketList,

    /**
     * The S3BucketListData model constructor.
     * @property {module:model/S3BucketListData}
     */
    S3BucketListData,

    /**
     * The S3Credentials model constructor.
     * @property {module:model/S3Credentials}
     */
    S3Credentials,

    /**
    * The DestinationsApi service constructor.
    * @property {module:api/DestinationsApi}
    */
    DestinationsApi,

    /**
    * The SourcesApi service constructor.
    * @property {module:api/SourcesApi}
    */
    SourcesApi,

    /**
    * The TransferApi service constructor.
    * @property {module:api/TransferApi}
    */
    TransferApi
};
