/**
 * Slice Doc Library - T3
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DigiMockerToken model module.
 * @module model/DigiMockerToken
 * @version 1.0.0
 */
class DigiMockerToken {
    /**
     * Constructs a new <code>DigiMockerToken</code>.
     * @alias module:model/DigiMockerToken
     */
    constructor() { 
        
        DigiMockerToken.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DigiMockerToken</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DigiMockerToken} obj Optional instance to populate.
     * @return {module:model/DigiMockerToken} The populated <code>DigiMockerToken</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DigiMockerToken();

            if (data.hasOwnProperty('access_token')) {
                obj['access_token'] = ApiClient.convertToType(data['access_token'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} access_token
 */
DigiMockerToken.prototype['access_token'] = undefined;






export default DigiMockerToken;

