/**
 * docxlib_js
 * This is api documentation for slice document library. Team `SLICE - T3`
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.DocxlibJs);
  }
}(this, function(expect, DocxlibJs) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new DocxlibJs.SourcesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SourcesApi', function() {
    describe('digiMockerSourceAuthCallback', function() {
      it('should call digiMockerSourceAuthCallback successfully', function(done) {
        //uncomment below and update the code to test digiMockerSourceAuthCallback
        //instance.digiMockerSourceAuthCallback(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('digimockerSourceAuth', function() {
      it('should call digimockerSourceAuth successfully', function(done) {
        //uncomment below and update the code to test digimockerSourceAuth
        //instance.digimockerSourceAuth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('digimockerSourceListFiles', function() {
      it('should call digimockerSourceListFiles successfully', function(done) {
        //uncomment below and update the code to test digimockerSourceListFiles
        //instance.digimockerSourceListFiles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gDriveSourceAuth', function() {
      it('should call gDriveSourceAuth successfully', function(done) {
        //uncomment below and update the code to test gDriveSourceAuth
        //instance.gDriveSourceAuth(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gDriveSourceAuthCallback', function() {
      it('should call gDriveSourceAuthCallback successfully', function(done) {
        //uncomment below and update the code to test gDriveSourceAuthCallback
        //instance.gDriveSourceAuthCallback(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('gDriveSourceListFiles', function() {
      it('should call gDriveSourceListFiles successfully', function(done) {
        //uncomment below and update the code to test gDriveSourceListFiles
        //instance.gDriveSourceListFiles(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
